version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/silta-node/12-alpine"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker"
    directory: "/silta-node/14-alpine"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker"
    directory: "/silta-node/16-alpine"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker"
    directory: "/silta-node/18-alpine"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker"
    directory: "/silta-node/lts-alpine"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "docker"
    directory: "/silta-nginx/1.17"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: "docker"
    directory: "/silta-nginx/1.19"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: "docker"
    directory: "/silta-nginx/1.21"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: "docker"
    directory: "/silta-nginx/1.23"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "docker"
    directory: "/silta-php-fpm/7.2-fpm"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: "docker"
    directory: "/silta-php-fpm/7.3-fpm"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: "docker"
    directory: "/silta-php-fpm/7.4-fpm"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: "docker"
    directory: "/silta-php-fpm/8.0-fpm"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: "docker"
    directory: "/silta-php-fpm/8.1-fpm"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: "docker"
    directory: "/silta-php-fpm/8.2-fpm"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "docker"
    directory: "/silta-varnish/varnish6"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
